In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.8 MB 5.6 MB/s eta 0:00:03
   --------- ------------------------------ 3.1/12.8 MB 7.1 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.8 MB 8.2 MB/s eta 0:00:01
   ------------------ --------------------- 6.0/12.8 MB 7.1 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.8 MB 7.9 MB/s eta 0:00:01
   -------------------------------- ------- 10.5/12.8 MB 8.2 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 8.5 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 8.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

Basic Array creation

In [3]:
arr=np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [4]:
a=[1,2,3.45,"hi"]
a

[1, 2, 3.45, 'hi']

In [6]:
arr2=np.array(a)
arr2

array(['1', '2', '3.45', 'hi'], dtype='<U32')

In [7]:
l=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation function

In [11]:
arr3=np.arange(1,101,2)
arr3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])