Array Operations

In [2]:
import numpy as np

Arithematic Operation

In [3]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1
a2

array([ 6,  7,  8,  9, 10])

In [4]:
arr=a1+a2
arr

array([ 7,  9, 11, 13, 15])

In [6]:
arr1=a2-a1
arr1

array([5, 5, 5, 5, 5])

In [7]:
arr3=a1*a2
arr3

array([ 6, 14, 24, 36, 50])

In [10]:
arr4=a1/a2
arr4

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
a1//a2

array([0, 0, 0, 0, 0])

In [13]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting


In [18]:
l=[10,20,30,40,50]
arr=np.array(l)
arr

array([10, 20, 30, 40, 50])

In [20]:
arr+10

array([20, 30, 40, 50, 60])

In [29]:
arr2=np.arange(1,26).reshape(5,5)
arr3= np.arange(1,26).reshape(5,5)
arr2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
arr2*arr3

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

Deep and Shallow Copy

In [55]:
a=np.arange(1,26)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [56]:
slice_a=a[:10]
slice_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
slice_a=slice_a*10
slice_a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [58]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [59]:
a[4:6]*10

array([50, 60])

In [60]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [61]:
a
b=a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [62]:
b[0]=1000
b

array([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25])

In [63]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])