In [2]:
import numpy as np

Numpy indexing and slicing of vectors

In [3]:
arr=np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[9]

np.int64(20)

In [ ]:
arr[1:5]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
arr[:5]

array([11, 12, 13, 14, 15])

In [13]:
arr[3::2]

array([14, 16, 18, 20])